spring.application.name=proyectoFinal

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.ukyfddhojzjmljcreucu
spring.datasource.password=Brais1705..

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true